<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';

if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<?php if ( $block->isLoggedIn() ) : ?>   
<li class="authorization-link authorization-link__dropdown-widget" data-label="<?= $block->escapeHtml(__('or')) ?>">
     <span class="action "
          data-toggle="dropdown"
          aria-haspopup="true"
          data-mage-init='{"dropdown":{}}'>
        <span class="label"><?= ucfirst(__('hello')) ?> <?= $block->escapeHtml($block->getCustomerName()) ?></span>
     </span>
     <ul class="dropdown-options dropdown" data-target="dropdown">
        <li class="my-account-link">
            <a href="<?= /*noEscape */ $block->getAccountUrl() ?>"><?= $block->escapeHtml(__('My Account')) ?></a>
        </li>
        <li class="logout-link">
            <span class="item"><a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>><?= $block->escapeHtml($block->getLabel()) ?></a></span>
        </li>
         
     </ul>
</li>
<?php else : ?>
<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
<?php endif ?>
