<?php

  $categoriesList = $block->getCategories();
  $sliderId = $block->getNameInLayout();

  if(count($categoriesList)) : 
?>
<?php 
    $baseUrl = $block->getStoreManagerData()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
    $blockTitle = $block->getCategoryTitle() ?? $block->getCategoryTitle();
?>
<div class="brands">
    <div class="inner brands-list">
        <?php if(!$block->isCategoryPage()) : ?>
        <h2><?= __($blockTitle) ?></h2>
        <?php endif ?>
        <div class="content">
            <ul id="slider-<?= $sliderId ?>" >
            <?php foreach ($categoriesList as $category) : if($category->getImage()) : ?>
                <li><a href="<?= $category->getUrl() ?>"><img alt="<?= $category->getName() ?>" src="<?= $baseUrl.$category->getImage() ?>"></a></li>
            <?php endif; 
          endforeach ?>
            </ul>
            <?php if(!$block->isCategoryPage()) : ?>
            <button type="button" class="button button-all-categories action primary" data-href="<?php echo $block->getCategoryUrl(); ?>"><?= __('See All') ?></button>
            <?php endif ?>
        </div>
    </div>
</div>
<?php if(!$block->isCategoryPage()) : ?>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {

        $('[data-href]').on('click',function(){
          window.location = $(this).data('href');
        });

        $(document).ready(function () {
            $('#slider-<?= $sliderId ?>').slick({
                dots: true,
                infinite: false,
                speed: 300,
                slidesToShow: 8,
                slidesToScroll: 8,
                dots: false,
                centerMode: false,
                variableWidth: false,
                responsive: [
                {
                  breakpoint: 1024,
                  settings: {
                    slidesToShow: 4,
                    slidesToScroll: 4,
                    infinite: true,
                    centerMode: false,
                    variableWidth: false,
                  }
                },
                {
                  breakpoint: 600,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2,
                    centerMode: false,
                    variableWidth: false,
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerMode: true,
                    variableWidth: true
                  }
                }
              ]
            });
        });
    });
</script>
<?php endif ?>
<?php endif ?>